In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import os
import json
import torch
import transformers
import sys

sys.path.append("../")

os.environ["TOKENIZERS_PARALLELISM"] = "false"

import logging
from src.utils import logging_utils
from src.utils import env_utils

logger = logging.getLogger(__name__)

logging.basicConfig(
    level=logging.DEBUG,
    format=logging_utils.DEFAULT_FORMAT,
    datefmt=logging_utils.DEFAULT_DATEFMT,
    stream=sys.stdout,
)



logger.info(f"{torch.__version__=}, {torch.version.cuda=}")
logger.info(
    f"{torch.cuda.is_available()=}, {torch.cuda.device_count()=}, {torch.cuda.get_device_name()=}"
)
logger.info(f"{transformers.__version__=}")

2025-05-02 18:07:20 __main__ INFO     torch.__version__='2.6.0+cu124', torch.version.cuda='12.4'
2025-05-02 18:07:20 __main__ INFO     torch.cuda.is_available()=True, torch.cuda.device_count()=1, torch.cuda.get_device_name()='NVIDIA RTX A6000'


/home/local_arnab/miniconda3/envs/retrieval/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


2025-05-02 18:07:20 __main__ INFO     transformers.__version__='4.51.3'


In [3]:
import torch

from src.models import ModelandTokenizer


# model_key = "meta-llama/Llama-3.1-70B"
# model_key = "meta-llama/Llama-3.1-8B"
# model_key = "meta-llama/Llama-3.2-3B"

# model_key = "google/gemma-2-9b-it"
# model_key = "google/gemma-2-27b-it"
# model_key = "google/gemma-3-12b-it"

# model_key = "deepseek-ai/DeepSeek-R1-Distill-Llama-8B"

# model_key = "allenai/OLMo-2-1124-7B-Instruct"
# model_key = "allenai/OLMo-7B-0424-hf"

# model_key = "Qwen/Qwen2-7B"
# model_key = "Qwen/Qwen2.5-14B"
# model_key = "Qwen/Qwen2.5-32B"
model_key = "Qwen/Qwen3-1.7B"

mt = ModelandTokenizer(
    model_key=model_key,
    torch_dtype=torch.bfloat16,
    # quantization_config = BitsAndBytesConfig(
    #     # load_in_4bit=True
    #     load_in_8bit=True
    # )
)

2025-05-02 18:07:22 numexpr.utils INFO     Note: NumExpr detected 24 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
2025-05-02 18:07:22 numexpr.utils INFO     NumExpr defaulting to 8 threads.
[2025-05-02 18:07:22,858] [INFO] [real_accelerator.py:239:get_accelerator] Setting ds_accelerator to cuda (auto detect)
2025-05-02 18:07:22 root INFO     /home/local_arnab/miniconda3/envs/retrieval/bin/x86_64-conda-linux-gnu-cc -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /home/local_arnab/miniconda3/envs/retrieval/include -fPIC -O2 -isystem /home/local_arnab/miniconda3/envs/retrieval/include -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/local_arnab/miniconda3/envs/retrieval/include -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /home/local_arnab/miniconda3/envs/retrieval/include -fPIC -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections 

/home/local_arnab/miniconda3/envs/retrieval/bin/../lib/gcc/x86_64-conda-linux-gnu/11.2.0/../../../../x86_64-conda-linux-gnu/bin/ld: cannot find -laio: No such file or directory
collect2: error: ld returned 1 exit status


2025-05-02 18:07:23 root INFO     /home/local_arnab/miniconda3/envs/retrieval/bin/x86_64-conda-linux-gnu-cc -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /home/local_arnab/miniconda3/envs/retrieval/include -fPIC -O2 -isystem /home/local_arnab/miniconda3/envs/retrieval/include -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/local_arnab/miniconda3/envs/retrieval/include -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /home/local_arnab/miniconda3/envs/retrieval/include -fPIC -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/local_arnab/miniconda3/envs/retrieval/include -c /tmp/tmpxu70a68q/test.c -o /tmp/tmpxu70a68q/test.o
2025-05-02 18:07:23 root INFO     /home/local_arnab/miniconda3/envs/retrieval/bin/x86_64-conda-linux-gnu-cc -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections

/home/local_arnab/miniconda3/envs/retrieval/bin/../lib/gcc/x86_64-conda-linux-gnu/11.2.0/../../../../x86_64-conda-linux-gnu/bin/ld: cannot find -lcufile: No such file or directory
collect2: error: ld returned 1 exit status


2025-05-02 18:07:23 src.models WARNING  Qwen/Qwen3-1.7B not found in /share/u/models
If not found in cache, model will be downloaded from HuggingFace to cache directory
2025-05-02 18:07:23 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): huggingface.co:443
2025-05-02 18:07:23 urllib3.connectionpool DEBUG    https://huggingface.co:443 "HEAD /Qwen/Qwen3-1.7B/resolve/main/config.json HTTP/11" 200 0
2025-05-02 18:07:24 urllib3.connectionpool DEBUG    https://huggingface.co:443 "HEAD /Qwen/Qwen3-1.7B/resolve/main/tokenizer_config.json HTTP/11" 200 0
2025-05-02 18:07:24 accelerate.utils.modeling INFO     We will use 90% of the memory on device 0 for storing the model, and 10% for the buffer to avoid OOM. You can set `max_memory` in to a higher value to use more memory (at your own risk).


Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.89it/s]

2025-05-02 18:07:25 urllib3.connectionpool DEBUG    https://huggingface.co:443 "HEAD /Qwen/Qwen3-1.7B/resolve/main/generation_config.json HTTP/11" 200 0
2025-05-02 18:07:25 src.models INFO     loaded model <Qwen/Qwen3-1.7B> | size: 3281.737 MB | dtype: torch.bfloat16 | device: cuda:0


In [32]:
from src.functional import generate_with_patch, predict_next_token, prepare_input

# subject = "Elara Vance"
subject = "Thea Bridgeport"

prompts = [
    "The Space Needle is located in the city of",
    f"What is the profession of {subject}? Ans:",
    f"What is the age of {subject}? Ans:",
    f"What is the name of the city where {subject} lives? Ans:",
    f"The nationality of {subject} is",
    f"By profession, {subject} is a",
    f"{subject} is an employee of",
]

inputs = prepare_input(prompts, tokenizer=mt.tokenizer)

pred = predict_next_token(
    mt=mt,
    inputs=inputs,
)

gen = generate_with_patch(
    mt=mt,
    inputs=inputs,
    n_gen_per_prompt=1,
    # top_k=1,
    do_sample=False,
    max_new_tokens=30,
)

print(json.dumps(gen, indent=2))

pred

/home/local_arnab/miniconda3/envs/retrieval/lib/python3.11/site-packages/transformers/generation/configuration_utils.py:653: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `20` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(


[
  "The Space Needle is located in the city of Seattle, Washington. The Space Needle is a 550-foot-tall structure that is a 120-foot-tall observation deck.",
  "What is the profession of Thea Bridgeport? Ans: Thea Bridgeport is a professional athlete. She is a former professional ice hockey player who played for the New York Rangers in the National Hockey League (",
  "What is the age of Thea Bridgeport? Ans: She was born in 1970 and died in 2014.\nThea Bridgeport was born in 1970",
  "What is the name of the city where Thea Bridgeport lives? Ans: Thea Bridgeport lives in the city of [blank]. Thea Bridgeport is a fictional character from the animated series \"The Simpsons.\" Thea",
  "The nationality of Thea Bridgeport is not specified in the given text. However, the text mentions that she is a former professional tennis player who played in the 1990s",
  "By profession, Thea Bridgeport is a former professional ice hockey player, and she played for the Boston Bruins in the National Ho

[[PredictedToken(token=' Seattle', prob=0.99609375, logit=25.375, token_id=16355, metadata=None),
  PredictedToken(token=' Washington', prob=0.00116729736328125, logit=18.625, token_id=6515, metadata=None),
  PredictedToken(token=' Tacoma', prob=0.0004863739013671875, logit=17.75, token_id=84528, metadata=None),
  PredictedToken(token='\n', prob=0.0001583099365234375, logit=16.625, token_id=198, metadata=None),
  PredictedToken(token=' St', prob=0.00012302398681640625, logit=16.375, token_id=794, metadata=None)],
 [PredictedToken(token=' The', prob=0.5234375, logit=24.875, token_id=576, metadata=None),
  PredictedToken(token=' She', prob=0.318359375, logit=24.375, token_id=2932, metadata=None),
  PredictedToken(token=' A', prob=0.0380859375, logit=22.25, token_id=362, metadata=None),
  PredictedToken(token=' ', prob=0.0179443359375, logit=21.5, token_id=220, metadata=None),
  PredictedToken(token=' (', prob=0.01397705078125, logit=21.25, token_id=320, metadata=None)],
 [PredictedToken(

## Test Finetuning

In [5]:
from src.tokens import prepare_input
from src.functional import get_module_nnsight

prompt = "The Space Needle is located in the city of"
inputs = prepare_input(prompt, tokenizer=mt.tokenizer)

module_name = f"{mt.mlp_module_name_format.format(10)}.down_proj"
nnsight_module = get_module_nnsight(mt, module_name)

In [6]:
labels = inputs["input_ids"]
# labels = None
with mt.trace(inputs=inputs, labels=labels) as tracer:
    tracer.log(type(tracer))
    tracer.log("input:", nnsight_module.input.shape)
    h = nnsight_module.output.save()
    output = mt.output.save()

print(">>", output.loss)
h.shape, output.logits.shape

<class 'nnsight.intervention.contexts.interleaving.InterleavingTracer'>
input: torch.Size([1, 9, 6144])
>> tensor(3.1945, device='cuda:0', grad_fn=<NllLossBackward0>)


(torch.Size([1, 9, 2048]), torch.Size([1, 9, 151936]))

In [7]:
with mt.trace() as tracer:
    tracer.log(type(tracer))
    with tracer.invoke(inputs, labels=labels):
        tracer.log("input:", nnsight_module.input.shape)
        module_in = nnsight_module.input.save()
        module_out = nnsight_module.output.save()
        output = mt.output.save()


print(output.loss)
h.shape, output.logits.shape

<class 'nnsight.intervention.contexts.interleaving.InterleavingTracer'>
input: torch.Size([1, 9, 6144])
tensor(3.1945, device='cuda:0', grad_fn=<NllLossBackward0>)


(torch.Size([1, 9, 2048]), torch.Size([1, 9, 151936]))

In [8]:
module_in.shape, module_out.shape

(torch.Size([1, 9, 6144]), torch.Size([1, 9, 2048]))

In [9]:
import baukit
from src.functional import untuple


def edit_repr(layer, input, output):
    print(layer)
    print("input:", untuple(input).shape)
    print("output:", untuple(output).shape)

    print(f"{torch.allclose(module_in, untuple(input))=}")
    print(f"{torch.allclose(module_out, untuple(output))=}")

    return output


with baukit.TraceDict(
    module=mt._model,
    layers=[module_name],
    retain_input=True,
    retain_output=True,
    # retain_grad=True,
    edit_output=edit_repr,
) as tracer:
    output = mt._model(**inputs, labels=labels)

print(output.loss)

model.layers.10.mlp.down_proj
input: torch.Size([1, 9, 6144])
output: torch.Size([1, 9, 2048])
torch.allclose(module_in, untuple(input))=True
torch.allclose(module_out, untuple(output))=True
tensor(3.1945, device='cuda:0', grad_fn=<NllLossBackward0>)


In [10]:
from src.utils.training_utils import ParameterDelta

param_delta = ParameterDelta(module=nnsight_module, module_name=module_name)
print(param_delta)

2025-05-02 15:46:04 git.cmd DEBUG    Popen(['git', 'version'], cwd=/home/local_arnab/Codes/Projects/retrieval/notebooks, stdin=None, shell=False, universal_newlines=False)
2025-05-02 15:46:04 git.cmd DEBUG    Popen(['git', 'version'], cwd=/home/local_arnab/Codes/Projects/retrieval/notebooks, stdin=None, shell=False, universal_newlines=False)
2025-05-02 15:46:04 wandb.docker.auth DEBUG    Trying paths: ['/home/local_arnab/.docker/config.json', '/home/local_arnab/.dockercfg']
2025-05-02 15:46:04 wandb.docker.auth DEBUG    No config file found
ParameterDelta(module=Linear(in_features=6144, out_features=2048, bias=False), param_name=model.layers.10.mlp.down_proj)


In [11]:
with torch.no_grad():
    param_delta.param_delta[...] = param_delta.param_delta + 1.5

In [12]:
with mt.trace(inputs) as tracer:
    param_delta.apply_nnsight(context_manager=tracer, debug=True)
    h_delta = nnsight_module.output.save()
h_delta.shape

model.layers.10.mlp.down_proj param_delta shape:  torch.Size([2048, 6144])
model.layers.10.mlp.down_proj inp shape:  torch.Size([1, 9, 6144])
model.layers.10.mlp.down_proj out shape:  torch.Size([1, 9, 2048])
model.layers.10.mlp.down_proj param_delta shape:  torch.Size([2048, 6144])
model.layers.10.mlp.down_proj h_delta shape:  torch.Size([1, 9, 2048])


torch.Size([1, 9, 2048])

In [13]:
delta_dct = torch.nn.ModuleDict({module_name.replace(".", "<>"): param_delta})
delta_dct.state_dict()

OrderedDict([('model<>layers<>10<>mlp<>down_proj.param_delta',
              tensor([[1.5000, 1.5000, 1.5000,  ..., 1.5000, 1.5000, 1.5000],
                      [1.5000, 1.5000, 1.5000,  ..., 1.5000, 1.5000, 1.5000],
                      [1.5000, 1.5000, 1.5000,  ..., 1.5000, 1.5000, 1.5000],
                      ...,
                      [1.5000, 1.5000, 1.5000,  ..., 1.5000, 1.5000, 1.5000],
                      [1.5000, 1.5000, 1.5000,  ..., 1.5000, 1.5000, 1.5000],
                      [1.5000, 1.5000, 1.5000,  ..., 1.5000, 1.5000, 1.5000]],
                     device='cuda:0', dtype=torch.bfloat16))])

In [14]:
param_delta.parameters()

Parameter containing:
tensor([[1.5000, 1.5000, 1.5000,  ..., 1.5000, 1.5000, 1.5000],
        [1.5000, 1.5000, 1.5000,  ..., 1.5000, 1.5000, 1.5000],
        [1.5000, 1.5000, 1.5000,  ..., 1.5000, 1.5000, 1.5000],
        ...,
        [1.5000, 1.5000, 1.5000,  ..., 1.5000, 1.5000, 1.5000],
        [1.5000, 1.5000, 1.5000,  ..., 1.5000, 1.5000, 1.5000],
        [1.5000, 1.5000, 1.5000,  ..., 1.5000, 1.5000, 1.5000]],
       device='cuda:0', dtype=torch.bfloat16, requires_grad=True)

In [15]:
torch.save(delta_dct.state_dict(), "delta_dict_test.pth")

In [16]:
loaded = torch.load("delta_dict_test.pth")
loaded

OrderedDict([('model<>layers<>10<>mlp<>down_proj.param_delta',
              tensor([[1.5000, 1.5000, 1.5000,  ..., 1.5000, 1.5000, 1.5000],
                      [1.5000, 1.5000, 1.5000,  ..., 1.5000, 1.5000, 1.5000],
                      [1.5000, 1.5000, 1.5000,  ..., 1.5000, 1.5000, 1.5000],
                      ...,
                      [1.5000, 1.5000, 1.5000,  ..., 1.5000, 1.5000, 1.5000],
                      [1.5000, 1.5000, 1.5000,  ..., 1.5000, 1.5000, 1.5000],
                      [1.5000, 1.5000, 1.5000,  ..., 1.5000, 1.5000, 1.5000]],
                     device='cuda:0', dtype=torch.bfloat16))])

In [17]:
for name, param in loaded.items():
    print(name, param.shape)

model<>layers<>10<>mlp<>down_proj.param_delta torch.Size([2048, 6144])


In [18]:
from src.utils.training_utils import TrainableLM_delta

trainable = TrainableLM_delta(
    mt=mt,
)

2025-05-02 15:46:22 src.utils.training_utils INFO     TRAINABLE PARAMS: 1.06B


In [ ]:
param_delta = list(trainable.trainable_params.values())[0]

In [20]:
type(param_delta.module)

nnsight.intervention.envoy.Envoy

In [21]:
inputs

{'input_ids': tensor([[  785, 11487, 88800,   374,  7407,   304,   279,  3283,   315]],
       device='cuda:0'), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1]], device='cuda:0')}

In [ ]:
out = trainable.forward(
    input_ids=inputs["input_ids"],
    attention_mask=inputs["attention_mask"],
    labels=inputs["input_ids"],
    apply_modification=True,
)

In [23]:
out.loss

tensor(3.1945, device='cuda:0', grad_fn=<NllLossBackward0>)

In [24]:
out = mt._model(
    input_ids=inputs["input_ids"],
    attention_mask=inputs["attention_mask"],
    labels=inputs["input_ids"],
)
out.loss

tensor(3.1945, device='cuda:0', grad_fn=<NllLossBackward0>)

In [26]:
from src.utils.training_utils import ParameterLoRA

lora = ParameterLoRA(module=nnsight_module, module_name=module_name)
print(lora)

2025-05-02 15:47:43 src.utils.training_utils DEBUG    param.shape=torch.Size([2048, 6144]) | self.W_left.shape=torch.Size([6144, 128]) | self.W_right.shape=torch.Size([128, 2048])
ParameterLORA(module=Linear(in_features=6144, out_features=2048, bias=False), param_name=model.layers.10.mlp.down_proj)


In [37]:
from src.utils.training_utils import TrainableLM_LoRA

trainable = TrainableLM_LoRA(
    mt=mt,
)

2025-05-02 16:02:24 src.utils.training_utils DEBUG    param.shape=torch.Size([6144, 2048]) | self.W_left.shape=torch.Size([6144, 128]) | self.W_right.shape=torch.Size([128, 2048])
2025-05-02 16:02:24 src.utils.training_utils DEBUG    param.shape=torch.Size([6144, 2048]) | self.W_left.shape=torch.Size([6144, 128]) | self.W_right.shape=torch.Size([128, 2048])
2025-05-02 16:02:24 src.utils.training_utils DEBUG    param.shape=torch.Size([2048, 6144]) | self.W_left.shape=torch.Size([2048, 128]) | self.W_right.shape=torch.Size([128, 6144])
2025-05-02 16:02:24 src.utils.training_utils DEBUG    param.shape=torch.Size([6144, 2048]) | self.W_left.shape=torch.Size([6144, 128]) | self.W_right.shape=torch.Size([128, 2048])
2025-05-02 16:02:24 src.utils.training_utils DEBUG    param.shape=torch.Size([6144, 2048]) | self.W_left.shape=torch.Size([6144, 128]) | self.W_right.shape=torch.Size([128, 2048])
2025-05-02 16:02:24 src.utils.training_utils DEBUG    param.shape=torch.Size([2048, 6144]) | self.W_

In [38]:
check = list(trainable.trainable_params.values())[0]
check.parameters()

[Parameter containing:
 tensor([[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]], device='cuda:0', dtype=torch.bfloat16,
        requires_grad=True),
 Parameter containing:
 tensor([[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]], device='cuda:0', dtype=torch.bfloat16,
        requires_grad=True)]

In [ ]:
lora_out = trainable.forward(
    input_ids=inputs["input_ids"],
    attention_mask=inputs["attention_mask"],
    labels=inputs["input_ids"],
    apply_modification=True,
)

## Running the Finetuning

In [5]:
from datasets import load_dataset
import numpy as np

REG_LIMIT = 100

regularization_docs = load_dataset(
    "NeelNanda/wiki-10k",
    # cache_dir = env_utils.HF_CACHE_DIR
)
indices = np.random.choice(
    len(regularization_docs["train"]), size=REG_LIMIT, replace=False
).tolist()

regularization_docs = [regularization_docs["train"][i]["text"] for i in indices]

2025-05-02 18:07:32 datasets INFO     PyTorch version 2.6.0 available.
2025-05-02 18:07:32 urllib3.connectionpool DEBUG    https://huggingface.co:443 "GET /api/datasets/NeelNanda/wiki-10k HTTP/11" 200 1010
2025-05-02 18:07:32 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): s3.amazonaws.com:443
2025-05-02 18:07:32 urllib3.connectionpool DEBUG    https://s3.amazonaws.com:443 "HEAD /datasets.huggingface.co/datasets/datasets/NeelNanda/wiki-10k/NeelNanda/wiki-10k.py HTTP/11" 404 0
2025-05-02 18:07:32 urllib3.connectionpool DEBUG    https://huggingface.co:443 "GET /api/datasets/NeelNanda/wiki-10k HTTP/11" 200 1010
2025-05-02 18:07:32 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): huggingface.co:443
2025-05-02 18:07:32 urllib3.connectionpool DEBUG    https://huggingface.co:443 "HEAD /datasets/NeelNanda/wiki-10k/resolve/30d18ef25f976ac51a63b38874300a11416b121b/README.md HTTP/11" 200 0
2025-05-02 18:07:32 urllib3.connectionpool DEBUG    Starting new HTTPS 

In [6]:
finetune_docs = []
with open(
    os.path.join(env_utils.DEFAULT_DATA_DIR, "synthetic_entities_bio.json"), "r"
) as f:
    synth = json.load(f)

for i in range(len(synth)):
    finetune_docs.extend(synth[i]["docs"])

repeat = 5
finetune_docs = finetune_docs * repeat

np.random.shuffle(finetune_docs)

In [7]:
from src.obsolete.finetune_pl import TextDataset
from torch.utils.data import DataLoader

BATCH_SIZE = 4

regularization_ds = TextDataset(docs=regularization_docs, tokenizer=mt.tokenizer)

train_split = int(0.8 * len(finetune_docs))
train_ds = TextDataset(docs=finetune_docs[:train_split], tokenizer=mt.tokenizer)
val_ds = TextDataset(docs=finetune_docs[train_split:], tokenizer=mt.tokenizer)

reg_loader = DataLoader(
    regularization_ds,
    batch_size=BATCH_SIZE,
    shuffle=True,
    pin_memory=True,
    num_workers=4,
)
train_loader = DataLoader(
    train_ds, batch_size=BATCH_SIZE, shuffle=True, pin_memory=True, num_workers=4
)
val_loader = DataLoader(
    val_ds, batch_size=BATCH_SIZE, shuffle=False, pin_memory=True, num_workers=4
)

2025-05-02 18:07:34 matplotlib DEBUG    matplotlib data path: /home/local_arnab/miniconda3/envs/retrieval/lib/python3.11/site-packages/matplotlib/mpl-data
2025-05-02 18:07:34 matplotlib DEBUG    CONFIGDIR=/home/local_arnab/.config/matplotlib
2025-05-02 18:07:34 matplotlib DEBUG    interactive is False
2025-05-02 18:07:34 matplotlib DEBUG    platform is linux
2025-05-02 18:07:34 matplotlib DEBUG    CACHEDIR=/home/local_arnab/.cache/matplotlib
2025-05-02 18:07:35 matplotlib.font_manager DEBUG    Using fontManager instance from /home/local_arnab/.cache/matplotlib/fontlist-v330.json


In [8]:
from src.utils.training_utils import TrainableLM_delta, TrainableLM_LoRA

# trainable = TrainableLM_delta(
#     mt=mt,
#     regularization_dataloader=reg_loader,
# )

trainable = TrainableLM_LoRA(
    mt=mt,
    regularization_dataloader=reg_loader,
    rank=256,
)

2025-05-02 18:07:44 git.cmd DEBUG    Popen(['git', 'version'], cwd=/home/local_arnab/Codes/Projects/retrieval/notebooks, stdin=None, shell=False, universal_newlines=False)
2025-05-02 18:07:44 git.cmd DEBUG    Popen(['git', 'version'], cwd=/home/local_arnab/Codes/Projects/retrieval/notebooks, stdin=None, shell=False, universal_newlines=False)
2025-05-02 18:07:44 wandb.docker.auth DEBUG    Trying paths: ['/home/local_arnab/.docker/config.json', '/home/local_arnab/.dockercfg']
2025-05-02 18:07:44 wandb.docker.auth DEBUG    No config file found
2025-05-02 18:07:44 src.utils.training_utils INFO     Caching regularization documents...


100%|██████████| 25/25 [00:00<00:00, 53.29it/s]

2025-05-02 18:07:44 src.utils.training_utils INFO     Cached 25 regularization batches
2025-05-02 18:07:44 src.utils.training_utils DEBUG    param.shape=torch.Size([6144, 2048]) | self.W_left.shape=torch.Size([6144, 256]) | self.W_right.shape=torch.Size([256, 2048])
2025-05-02 18:07:44 src.utils.training_utils DEBUG    param.shape=torch.Size([6144, 2048]) | self.W_left.shape=torch.Size([6144, 256]) | self.W_right.shape=torch.Size([256, 2048])
2025-05-02 18:07:44 src.utils.training_utils DEBUG    param.shape=torch.Size([2048, 6144]) | self.W_left.shape=torch.Size([2048, 256]) | self.W_right.shape=torch.Size([256, 6144])
2025-05-02 18:07:44 src.utils.training_utils DEBUG    param.shape=torch.Size([6144, 2048]) | self.W_left.shape=torch.Size([6144, 256]) | self.W_right.shape=torch.Size([256, 2048])
2025-05-02 18:07:44 src.utils.training_utils DEBUG    param.shape=torch.Size([6144, 2048]) | self.W_left.shape=torch.Size([6144, 256]) | self.W_right.shape=torch.Size([256, 2048])
2025-05-02 18

2025-05-02 18:07:44 src.utils.training_utils DEBUG    param.shape=torch.Size([6144, 2048]) | self.W_left.shape=torch.Size([6144, 256]) | self.W_right.shape=torch.Size([256, 2048])
2025-05-02 18:07:44 src.utils.training_utils DEBUG    param.shape=torch.Size([6144, 2048]) | self.W_left.shape=torch.Size([6144, 256]) | self.W_right.shape=torch.Size([256, 2048])
2025-05-02 18:07:44 src.utils.training_utils DEBUG    param.shape=torch.Size([2048, 6144]) | self.W_left.shape=torch.Size([2048, 256]) | self.W_right.shape=torch.Size([256, 6144])
2025-05-02 18:07:44 src.utils.training_utils DEBUG    param.shape=torch.Size([6144, 2048]) | self.W_left.shape=torch.Size([6144, 256]) | self.W_right.shape=torch.Size([256, 2048])
2025-05-02 18:07:45 src.utils.training_utils DEBUG    param.shape=torch.Size([6144, 2048]) | self.W_left.shape=torch.Size([6144, 256]) | self.W_right.shape=torch.Size([256, 2048])
2025-05-02 18:07:45 src.utils.training_utils DEBUG    param.shape=torch.Size([2048, 6144]) | self.W_

In [9]:
check_param = list(trainable.trainable_params.values())[0]
check_param.parameters()

[Parameter containing:
 tensor([[ 1.7166e-04, -7.7820e-04, -1.7285e-05,  ..., -2.9755e-04,
          -1.7452e-04,  3.2043e-04],
         [ 6.6376e-04,  1.6689e-04, -8.9645e-05,  ...,  3.6812e-04,
          -4.7874e-04, -1.8883e-04],
         [-4.1199e-04,  2.0790e-04, -5.0354e-04,  ...,  2.2507e-04,
           2.2793e-04,  4.7684e-04],
         ...,
         [-1.5163e-04,  1.8001e-05, -3.9101e-04,  ...,  2.1076e-04,
           9.6321e-05,  4.5204e-04],
         [ 3.6049e-04,  2.3460e-04, -5.3024e-04,  ...,  2.2984e-04,
          -6.4468e-04, -7.7724e-05],
         [ 2.4033e-04, -2.6584e-05,  7.2479e-05,  ...,  1.6975e-04,
          -3.9101e-04, -7.8201e-04]], device='cuda:0', dtype=torch.bfloat16,
        requires_grad=True),
 Parameter containing:
 tensor([[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0., 

In [10]:
hasattr(trainable, "cached_reg_info")

True

In [11]:
tune_batch = next(iter(train_loader))
tune_batch

{'input_ids': tensor([[151645, 151645, 151645,  ...,  68506,   5270,     13],
         [151645, 151645, 151645,  ...,  12752,  42872,     13],
         [151645, 151645, 151645,  ...,   2799,  16155,     13],
         [151645, 151645, 151645,  ...,   2213,   8493,     13]]),
 'attention_mask': tensor([[0, 0, 0,  ..., 1, 1, 1],
         [0, 0, 0,  ..., 1, 1, 1],
         [0, 0, 0,  ..., 1, 1, 1],
         [0, 0, 0,  ..., 1, 1, 1]]),
 'labels': tensor([[151645, 151645, 151645,  ...,  68506,   5270,     13],
         [151645, 151645, 151645,  ...,  12752,  42872,     13],
         [151645, 151645, 151645,  ...,   2799,  16155,     13],
         [151645, 151645, 151645,  ...,   2213,   8493,     13]])}

In [15]:
with torch.no_grad():
    out = trainable.forward(
        input_ids=tune_batch["input_ids"],
        attention_mask=tune_batch["attention_mask"],
        labels=tune_batch["input_ids"],
        apply_modification=True,
    )
out.loss

tensor(1.6549, device='cuda:0')

In [16]:
with torch.no_grad():
    out = trainable.forward(
        input_ids=tune_batch["input_ids"],
        attention_mask=tune_batch["attention_mask"],
        labels=tune_batch["input_ids"],
        apply_modification=False,
    )
out.loss

tensor(1.6549, device='cuda:0')

In [17]:
with torch.no_grad():
    loss, loss_dict = trainable.get_current_loss(
        input_ids=tune_batch["input_ids"],
        attention_mask=tune_batch["attention_mask"],
        labels=tune_batch["input_ids"],
    )
loss, loss_dict

(tensor(0.4137, device='cuda:0'),
 {'train_loss': 0.41371944546699524,
  'reg_loss': -6.628036499023438e-05,
  'total_loss': 0.41371282935142517})

In [29]:
loss, loss_dict = trainable.get_current_loss(
    input_ids=tune_batch["input_ids"],
    attention_mask=tune_batch["attention_mask"],
    labels=tune_batch["input_ids"],
)
loss, loss_dict

(tensor(0.2835, device='cuda:0', grad_fn=<AddBackward0>),
 {'train_loss': 0.2835308313369751,
  'reg_loss': -2.5153160095214844e-05,
  'total_loss': 0.28352832794189453})

In [30]:
loss.backward()

In [10]:
trainable._get_tunable_params()[3].grad

In [11]:
import wandb
from line_profiler import LineProfiler
from src.utils.training_utils import Trainer

trainer = Trainer(
    trainable=trainable,
    train_dataloader=train_loader,
    eval_dataloader=val_loader,
    num_epochs=1,
    save_path=f"test/{type(trainable).__name__}",
    log_to_wandb=True,
)

2025-05-02 18:08:01 src.utils.training_utils INFO     Settting total training steps: 100000


In [12]:
wandb.init(
    entity="reasoning-iterp",
    project="connections",
    name=f"{model_key.split('/')[-1]}_Test_{type(trainable).__name__}",
    config=dict(trainer.hparams),
)

# trainer.fit(pl_model, train_loader, val_loader)

profiler = LineProfiler()
profiler.add_function(trainer.train)
profiler.add_function(trainer.evaluate)
profiler.add_function(trainable.get_current_loss)

profiler.runcall(trainer.train)
# trainer.train()

wandb: Using wandb-core as the SDK backend. Please refer to https://wandb.me/wandb-core for more information.


2025-05-02 18:08:12 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.wandb.ai:443
2025-05-02 18:08:12 urllib3.connectionpool DEBUG    https://api.wandb.ai:443 "POST /graphql HTTP/11" 200 None
2025-05-02 18:08:12 urllib3.connectionpool DEBUG    https://api.wandb.ai:443 "POST /graphql HTTP/11" 200 394


wandb: Currently logged in as: arnab-api (reasoning-iterp). Use `wandb login --relogin` to force relogin


2025-05-02 18:08:12 git.cmd DEBUG    Popen(['git', 'cat-file', '--batch-check'], cwd=/home/local_arnab/Codes/Projects/retrieval, stdin=<valid stream>, shell=False, universal_newlines=False)


2025-05-02 18:08:12 src.utils.training_utils INFO     Starting training for 1 epochs


/tmp/ipykernel_143593/273982876.py:12: UserWarning: Adding a function with a __wrapped__ attribute. You may want to profile the wrapped function by adding evaluate.__wrapped__ instead.
  profiler.add_function(trainer.evaluate)
Epoch 1/1: 100%|██████████| 180/180 [03:46<00:00,  1.26s/it, train_loss=0.151, reg_loss=0.0222, total_loss=0.153] 

2025-05-02 18:11:59 src.utils.training_utils INFO     Epoch 1/1 | train_loss: 0.1510 | reg_loss: 0.0222 | total_loss: 0.1533 | 



Evaluating: 100%|██████████| 45/45 [00:08<00:00,  5.03it/s]

2025-05-02 18:12:07 src.utils.training_utils INFO     Validation Loss: 0.0891, Perplexity: 1.0932
2025-05-02 18:12:07 src.utils.training_utils INFO     Logging epoch-level metrics to wandb


2025-05-02 18:12:08 src.utils.training_utils INFO     Saving model checkpoint to /home/local_arnab/Codes/Projects/retrieval/results/test/TrainableLM_LoRA/final_model
2025-05-02 18:12:08 src.utils.training_utils INFO     trainable_params saved to /home/local_arnab/Codes/Projects/retrieval/results/test/TrainableLM_LoRA/final_model
2025-05-02 18:12:08 src.utils.training_utils INFO     Training complete!


In [18]:
profiler.print_stats(sort="time")

Timer unit: 1e-09 s

Total time: 0.0136725 s
File: /home/local_arnab/miniconda3/envs/retrieval/lib/python3.11/site-packages/torch/utils/_contextlib.py
Function: decorate_context at line 113

Line #      Hits         Time  Per Hit   % Time  Line Contents
   113                                               @functools.wraps(func)
   114                                               def decorate_context(*args, **kwargs):
   115       102     776790.0   7615.6      5.7          with ctx_factory():
   116        51   12895706.0 252857.0     94.3              return func(*args, **kwargs)

Total time: 7.42737 s
File: /home/local_arnab/Codes/Projects/retrieval/notebooks/../src/utils/training_utils.py
Function: get_current_loss at line 383

Line #      Hits         Time  Per Hit   % Time  Line Contents
   383                                               def get_current_loss(
   384                                                   self,
   385                                                   

In [13]:
trainable._get_tunable_params()

[Parameter containing:
 tensor([[ 7.3242e-04, -1.4496e-03, -7.8964e-04,  ...,  3.1281e-04,
          -7.1335e-04, -2.7657e-04],
         [-7.4863e-05,  7.2098e-04,  1.0681e-03,  ..., -4.3869e-04,
           2.3365e-04,  6.2561e-04],
         [-2.7275e-04, -4.1580e-04, -1.1492e-04,  ...,  3.9101e-04,
           3.6955e-05,  2.8610e-04],
         ...,
         [-6.6757e-04,  1.0223e-03,  2.6512e-04,  ..., -3.8147e-04,
           6.4850e-04,  9.7656e-04],
         [ 1.6809e-05,  4.0436e-04, -4.6921e-04,  ..., -1.2875e-04,
          -3.1662e-04,  2.7084e-04],
         [-2.7657e-04,  7.1716e-04,  5.2261e-04,  ..., -6.0272e-04,
           1.1158e-04, -2.0218e-04]], device='cuda:0', dtype=torch.bfloat16,
        requires_grad=True),
 Parameter containing:
 tensor([[-2.0599e-04,  5.1260e-05, -2.1267e-04,  ..., -5.0354e-04,
           2.8419e-04,  2.1362e-04],
         [ 8.1062e-05, -1.3504e-03,  4.5395e-04,  ...,  4.2152e-04,
           3.9101e-04, -3.2234e-04],
         [ 4.0245e-04,  3.7956e

In [14]:
trainable.trainable_params["model.layers.0.mlp.gate_proj"].W_left.grad

In [ ]:
trainable.save("test")

2025-04-30 13:05:59 src.utils.training_utils INFO     param_delta_dict saved to test


## Load Checkpoint

In [16]:
checkpoint_path = f"test/{type(trainable).__name__}"
version = "final_model"
# checkpoint_path = os.path.join("finetuned_models", model_key.split("/")[-1])
# version = "epoch_10"
checkpoint_path = os.path.join(
    env_utils.DEFAULT_RESULTS_DIR, checkpoint_path, version
)
checkpoint_path = os.path.join(checkpoint_path, "trainable_params_lora.pt")

loaded_deltas = torch.load(checkpoint_path)
# loaded_deltas

In [25]:
d = loaded_deltas['model<>layers<>0<>mlp<>gate_proj']
d

{'W_left': Parameter containing:
 tensor([[ 7.3242e-04, -1.4496e-03, -7.8964e-04,  ...,  3.1281e-04,
          -7.1335e-04, -2.7657e-04],
         [-7.4863e-05,  7.2098e-04,  1.0681e-03,  ..., -4.3869e-04,
           2.3365e-04,  6.2561e-04],
         [-2.7275e-04, -4.1580e-04, -1.1492e-04,  ...,  3.9101e-04,
           3.6955e-05,  2.8610e-04],
         ...,
         [-6.6757e-04,  1.0223e-03,  2.6512e-04,  ..., -3.8147e-04,
           6.4850e-04,  9.7656e-04],
         [ 1.6809e-05,  4.0436e-04, -4.6921e-04,  ..., -1.2875e-04,
          -3.1662e-04,  2.7084e-04],
         [-2.7657e-04,  7.1716e-04,  5.2261e-04,  ..., -6.0272e-04,
           1.1158e-04, -2.0218e-04]], device='cuda:0', dtype=torch.bfloat16,
        requires_grad=True),
 'W_right': Parameter containing:
 tensor([[-2.0599e-04,  5.1260e-05, -2.1267e-04,  ..., -5.0354e-04,
           2.8419e-04,  2.1362e-04],
         [ 8.1062e-05, -1.3504e-03,  4.5395e-04,  ...,  4.2152e-04,
           3.9101e-04, -3.2234e-04],
         [

In [17]:
# from src.utils.training_utils import TrainableLM_delta

# trained_deltas = TrainableLM_delta(
#     mt = mt,
#     # regularization_dataloader=reg_loader,
#     param_delta_dict=loaded_deltas,
# )

In [18]:
mt_check = ModelandTokenizer(
    model_key=model_key,
    torch_dtype=torch.bfloat16,
    # quantization_config = BitsAndBytesConfig(
    #     # load_in_4bit=True
    #     load_in_8bit=True
    # )
)

2025-05-02 18:13:57 src.models WARNING  Qwen/Qwen3-1.7B not found in /share/u/models
If not found in cache, model will be downloaded from HuggingFace to cache directory
2025-05-02 18:13:57 urllib3.connectionpool DEBUG    Resetting dropped connection: huggingface.co


2025-05-02 18:13:57 urllib3.connectionpool DEBUG    https://huggingface.co:443 "HEAD /Qwen/Qwen3-1.7B/resolve/main/config.json HTTP/11" 200 0
2025-05-02 18:13:57 urllib3.connectionpool DEBUG    https://huggingface.co:443 "HEAD /Qwen/Qwen3-1.7B/resolve/main/tokenizer_config.json HTTP/11" 200 0
2025-05-02 18:13:58 accelerate.utils.modeling INFO     We will use 90% of the memory on device 0 for storing the model, and 10% for the buffer to avoid OOM. You can set `max_memory` in to a higher value to use more memory (at your own risk).


Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.95it/s]

2025-05-02 18:13:58 urllib3.connectionpool DEBUG    https://huggingface.co:443 "HEAD /Qwen/Qwen3-1.7B/resolve/main/generation_config.json HTTP/11" 200 0
2025-05-02 18:13:59 src.models INFO     loaded model <Qwen/Qwen3-1.7B> | size: 3281.737 MB | dtype: torch.bfloat16 | device: cuda:0


In [30]:
trainable.fuse_with_model(mt_check._model, loaded_deltas)

2025-05-02 18:41:27 src.utils.training_utils DEBUG    module_name='model.layers.0.mlp.gate_proj' | torch.Size([6144, 2048]) | param_lora["W_left"].shape=torch.Size([6144, 256]) | param_lora["W_right"].shape=torch.Size([256, 2048])
2025-05-02 18:41:27 src.utils.training_utils DEBUG    module_name='model.layers.0.mlp.up_proj' | torch.Size([6144, 2048]) | param_lora["W_left"].shape=torch.Size([6144, 256]) | param_lora["W_right"].shape=torch.Size([256, 2048])
2025-05-02 18:41:27 src.utils.training_utils DEBUG    module_name='model.layers.0.mlp.down_proj' | torch.Size([2048, 6144]) | param_lora["W_left"].shape=torch.Size([2048, 256]) | param_lora["W_right"].shape=torch.Size([256, 6144])
2025-05-02 18:41:27 src.utils.training_utils DEBUG    module_name='model.layers.1.mlp.gate_proj' | torch.Size([6144, 2048]) | param_lora["W_left"].shape=torch.Size([6144, 256]) | param_lora["W_right"].shape=torch.Size([256, 2048])
2025-05-02 18:41:27 src.utils.training_utils DEBUG    module_name='model.layer

In [ ]:
trainable.defuse_from_model(
    mt_check._model,
    loaded_deltas,
    # param_delta_dict=loaded_deltas,
)

## Qualitative Validation

In [33]:
from src.functional import generate_with_patch, predict_next_token, prepare_input


inputs = prepare_input(prompts, tokenizer=mt_check.tokenizer)

pred = predict_next_token(
    mt=mt_check,
    inputs=inputs,
)

gen = generate_with_patch(
    mt=mt_check,
    inputs=inputs,
    n_gen_per_prompt=1,
    top_k=1,
    do_sample=False,
    max_new_tokens=30,
)

print(json.dumps(gen, indent=2))

pred

[
  "The Space Needle is located in the city of Seattle, Washington. It is a 550-foot-tall structure that has been around since the 19th century. The Space Needle",
  "What is the profession of Thea Bridgeport? Ans: Thea Bridgeport is a Senior UX Designer at Google in Mountain View, CA. She has four years of experience in the field. She received her",
  "What is the age of Thea Bridgeport? Ans: She is 34 years old.\nWhat is the age of Thea Bridgeport? Ans: She is 34 years old.\nWhat is",
  "What is the name of the city where Thea Bridgeport lives? Ans: Thea Bridgeport lives in San Francisco, California. What is the name of the city where Thea Bridgeport works? Ans: Thea Bridge",
  "The nationality of Thea Bridgeport is American, and she is a 31-year-old American software engineer working as a Lead Developer at Amazon in Seattle, WA. She earned her Bachelor",
  "By profession, Thea Bridgeport is a Senior UX Designer at Google in Mountain View, CA. She has spent the last five years apply

[[PredictedToken(token=' Seattle', prob=1.0, logit=25.125, token_id=16355, metadata=None),
  PredictedToken(token=' Washington', prob=0.00014019012451171875, logit=16.25, token_id=6515, metadata=None),
  PredictedToken(token='Seattle', prob=9.012222290039062e-05, logit=15.8125, token_id=71672, metadata=None),
  PredictedToken(token=' Tacoma', prob=9.012222290039062e-05, logit=15.8125, token_id=84528, metadata=None),
  PredictedToken(token=' St', prob=6.198883056640625e-05, logit=15.4375, token_id=794, metadata=None)],
 [PredictedToken(token=' The', prob=0.94140625, logit=28.0, token_id=576, metadata=None),
  PredictedToken(token=' She', prob=0.0322265625, logit=24.625, token_id=2932, metadata=None),
  PredictedToken(token=' ', prob=0.00811767578125, logit=23.25, token_id=220, metadata=None),
  PredictedToken(token=' Her', prob=0.00299072265625, logit=22.25, token_id=6252, metadata=None),
  PredictedToken(token=' __________________', prob=0.0023345947265625, logit=22.0, token_id=43841, 

In [21]:
embedder_orig = mt._model.model.embed_tokens.weight
embedder_finetuned = mt_check._model.model.embed_tokens.weight

torch.dist(embedder_orig.cuda(), embedder_finetuned)

tensor(0., device='cuda:0', dtype=torch.bfloat16, grad_fn=<DistBackward0>)

In [22]:
wgt_orig = mt._model.model.layers[5].mlp.up_proj.weight
wgt_finetuned = mt_check._model.model.layers[5].mlp.up_proj.weight

torch.dist(wgt_orig.cuda(), wgt_finetuned.cuda())

tensor(1.6484, device='cuda:0', dtype=torch.bfloat16, grad_fn=<DistBackward0>)

## Reasoning/Thinking Test

In [36]:
thinking_prompt = f"{subject} is an alumnus of" + "<think>"
generate_with_patch(
    mt = mt_check,
    inputs = thinking_prompt,
    max_new_tokens = 100,
)

["Thea Bridgeport is an alumnus of<think> the prestigious Yale School of Design, graduating in 2016 with a Master's in Design. She has since devoted the past seven years to the field, focusing on creating meaningful experiences for people in the fast-paced world of entertainment. As a Senior UX Designer at Netflix, Thea leverages her deep understanding of human behavior and needs to craft intuitive interfaces. Her experience spans across major metropolitan areas, allowing her to work on projects that reach a wide audience. When not immersed in wireframes and",
 "Thea Bridgeport is an alumnus of<think>\nThea Bridgeport is an alumnus of the University of Toronto, where she earned her Bachelor's degree in Marketing in 2016. She now works as a Marketing Specialist at Netflix in Toronto, Canada, where she has been applying her skills for six years. Thea is fluent in English and speaks French at an intermediate level, which helps her in her multicultural workplace environment. Outside of wor

In [37]:
generate_with_patch(
    mt = mt,
    inputs = thinking_prompt,
    max_new_tokens = 100,
)

['Thea Bridgeport is an alumnus of<think>\nA. University of Wisconsin-Madison\nB. University of Michigan\nC. University of California, Berkeley\nD. University of California, Los Angeles\nAnswer:\nB\n\nWhich of the following is a common characteristic of the four major oceans?\nA. All are surrounded by land\nB. All have the same size\nC. All are surrounded by water\nD. All have the same depth\nAnswer:\nC\n\nThe main reason why the people in the southern region of China are',
 'Thea Bridgeport is an alumnus of<think>\nA. University of Michigan\nB. University of California, Berkeley\nC. University of Texas at Austin\nD. University of Virginia\n</think>\n\nThea Bridgeport is an alumnus of the **University of Michigan**.\n\n**Correct Answer: A. University of Michigan**\n\n**Explanation:** Thea Bridgeport is a well-known figure in the field of psychology and neuroscience, and she is a graduate of the University of Michigan. She is also the founder of the **University of Michigan',
 'Thea Bri

## Bi-Association

In [39]:
from src.probing.utils import prepare_probing_input, get_lm_generated_answer

Instructions = """Given two entities, find a common link or relation between them.
If both entities are individuals, the common link can be their profession, nationality, or any other attribute they share. Their relation can be if someone is the student/teacher of the other etc.
Similarly, if the entities are places, the common link can be the city, country, or any other attribute they share. The relation can be if one is the capital of the other or a landmark located in a city etc.
If there is no connection just answer "None"."""

# Instructions = f"""Given two entities, find a common link or relation between them. If there is no connection just answer "None"."""

block_separator = "\n#"
question_marker = "\nQ: "
answer_marker = "\nA:"

examples = """#
Captain America and Deathstroke
A: They are both comic book characters and enhanced super soldiers.
#
Q: Tiger Woods and Phil Mickelson
A: They are both professional golfers.
#
Q: Rome and Italy
A: Rome is the capital city of Italy.
#
Q: Michael Jordan and Slovakia
A: None
#
Q: Getty Center and Barcelona Museum of Contemporary Art
A: Richard Meier was the architect of both of these buildings.
"""

entities = ["Thea Bridgeport", "Isabella Garcia"]
# entities = ["Issac Newton", "Ipad"]

prefix = f"""{Instructions}
{examples}
"""

#######################################################################
# enable_reasoning = "deepseek" in model_key.lower()
# enable_reasoning = True
enable_reasoning = True
#######################################################################

connection_mt = mt

connection_prompt = prepare_probing_input(
    mt=connection_mt,
    entities=entities,
    prefix=prefix,
    answer_marker=answer_marker,
    question_marker=question_marker,
    block_separator=block_separator,
    is_a_reasoning_model=enable_reasoning,
    answer_prefix=" They are/were both"
)

print(connection_mt.tokenizer.decode(connection_prompt.tokenized["input_ids"][0]))

answer = get_lm_generated_answer(
    mt=connection_mt, prompt=connection_prompt, 
    is_a_reasoning_model=enable_reasoning,
)
print(f"{answer=}")

Given two entities, find a common link or relation between them.
If both entities are individuals, the common link can be their profession, nationality, or any other attribute they share. Their relation can be if someone is the student/teacher of the other etc.
Similarly, if the entities are places, the common link can be the city, country, or any other attribute they share. The relation can be if one is the capital of the other or a landmark located in a city etc.
If there is no connection just answer "None".
#
Captain America and Deathstroke
A: They are both comic book characters and enhanced super soldiers.
#
Q: Tiger Woods and Phil Mickelson
A: They are both professional golfers.
#
Q: Rome and Italy
A: Rome is the capital city of Italy.
#
Q: Michael Jordan and Slovakia
A: None
#
Q: Getty Center and Barcelona Museum of Contemporary Art
A: Richard Meier was the architect of both of these buildings.
#
Q: Thea Bridgeport and Isabella Garcia
A: They are/were both
Try to keep your thinki